version: '3.9'

##############################################################################
#
# services
#
##############################################################################
services:

  ####################
  # nlp:
  #
  nlp:
    build:
      context: ./nlp
      dockerfile: Dockerfile
    image: nghiadh/nlp:0.2.0
    hostname: nlp
    container_name: nlp
    networks:
      - backend
    ports:
      - 8000:8000
    volumes:
      - ./conf:/conf

  ####################
  # tika:
  #
  tika:
    image: apache/tika:1.25-full
    hostname: tika
    container_name: tika
    networks:
      - backend
    ports:
      - 9998:9998

  ####################
  # extractor:
  #
  extractor:
    build:
      context: ./extractor
      dockerfile: Dockerfile
    image: nghiadh/extractor:0.1.0
    hostname: extractor
    container_name: extractor
    networks:
      - backend
    ports:
      - 8002:8002
    volumes:
      - ./conf:/conf
      - ./import:/import

  ####################
  # neo4j:
  # - Neo4j + APOC + Apache POI + Graph Data Science
  #
  neo4j:
    image: neo4j:4.2.2
    hostname: neo4j
    container_name: neo4j
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    networks:
      - backend
    volumes:
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/pskgi
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_memory_heap_initial__size=2G
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_security_allow__csv__import__from__file__urls=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_jobs_pool_num__threads=4
      - NEO4J_apoc_jobs_scheduled_num__threads=4
      - NEO4J_apoc_http_timeout_connect=60000
      - NEO4J_apoc_http_timeout_read=120000
      - NEO4J_browser_remote__content__hostname__whitelist=*

  ####################
  # show:
  #
  show:
    build:
      context: ./show
      dockerfile: Dockerfile
    image: nghiadh/show:0.2.0
    hostname: show
    container_name: show
    ports:
      - 8001:8001

################################################################################
#
# networks
#
################################################################################
networks:
  backend:
