version: '3.9'

##############################################################################
#
# services
#
##############################################################################
services:

  ####################
  # nlp:
  #
  nlp:
    build:
      context: ./nlp
      dockerfile: Dockerfile
    image: nlp:0.0.1
    hostname: nlp
    container_name: nlp
    ports:
      - 8000:8000
    volumes:
      - ./conf:/conf
